#!/bin/bash
# Program to output a system information page
TITLE="System Information Report"
echo "<HTML>
      <HEAD>
            <TITLE>$TITLE</TITLE>
      </HEAD>
      <BODY>
	  	<H1>$TITLE</H1>
      </BODY>
</HTML>"
