#!/bin/bash
# Program to output a system information page
TITLE="System Information Report"
CURRENT_TIME=$(date +"%x %r %z")
TIME_STAMP="Generated $CURRENT_TIME, by $USER"

report_uptime() {
	cat <<- _EOF_
	<H2>System Uptime</H2>
	<PRE>$(uptime)</PRE>
	_EOF_

	return	
}

report_dis_space(){
	cat <<- _EOF_
	<H2>Disk Space Utilization</H2>
	<PRE>$(df -h)</PRE>
	_EOF_
	return
}
report_home_space(){
	if [[$(id -u) -eq 0]]; then
		cat <<- _EOF_
		<H2>Home Space Utilization(All Users)</H2>
		<PRE>$(du -sh /home/*)</PRE>
		_EOF_
	else
		cat <<- _EOF_
		<H2>Home Space Utilization($USER)</H2>
		<PRE>$(du -sh $HOME)</PRE>
		_EOF_
	fi
	return
}
dfdkfjksdfjksjfskdjf
#fuck
$$$$$;



